services:
  postgres:
    image: postgres:15-alpine
    container_name: tust_starter_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tust_starter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tust_starter_api
    environment:
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      DATABASE_URL: postgres://postgres:password@postgres:5432/tust_starter
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRATION_HOURS: 24
      RATE_LIMIT_RPS: 10
      RATE_LIMIT_BURST: 20
      ENV: development
      RUST_LOG: info,tust_starter=debug
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
